apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2023-03-08T12:00:44Z"
  generation: 1
  managedFields:
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:exclude.release.openshift.io/internal-openshift-hosted: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"df6fb9e8-7fcf-4dfa-9adc-ffb076bfb757"}: {}
      f:spec: {}
    manager: cluster-version-operator
    operation: Update
    time: "2023-03-08T12:00:44Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:extension: {}
    manager: cluster-version-operator
    operation: Update
    subresource: status
    time: "2023-03-08T12:00:44Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions: {}
        f:relatedObjects: {}
        f:versions: {}
    manager: authentication-operator
    operation: Update
    subresource: status
    time: "2023-03-08T12:19:57Z"
  name: authentication
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: df6fb9e8-7fcf-4dfa-9adc-ffb076bfb757
  resourceVersion: "12116"
  uid: 8ccbce32-2dad-4f2c-a1aa-bb1c9755f3f9
spec: {}
status:
  conditions:
  - lastTransitionTime: "2023-03-08T12:11:40Z"
    message: "IngressStateEndpointsDegraded: No subsets found for the endpoints of
      oauth-server\nOAuthClientsControllerDegraded: no ingress for host oauth-openshift.apps.vrutkovs.choomba.one
      in route oauth-openshift in namespace openshift-authentication\nOAuthServerDeploymentDegraded:
      waiting for the oauth-openshift route to contain an admitted ingress: no admitted
      ingress for route oauth-openshift in namespace openshift-authentication\nOAuthServerDeploymentDegraded:
      \nOAuthServerRouteEndpointAccessibleControllerDegraded: route \"openshift-authentication/oauth-openshift\":
      status does not have a valid host address\nOAuthServerServiceEndpointAccessibleControllerDegraded:
      Get \"https://172.30.76.170:443/healthz\": dial tcp 172.30.76.170:443: connect:
      connection refused\nOAuthServerServiceEndpointsEndpointAccessibleControllerDegraded:
      oauth service endpoints are not ready\nWellKnownReadyControllerDegraded: failed
      to get oauth metadata from openshift-config-managed/oauth-openshift ConfigMap:
      configmap \"oauth-openshift\" not found (check authentication operator, it is
      supposed to create this)"
    reason: IngressStateEndpoints_MissingSubsets::OAuthClientsController_SyncError::OAuthServerDeployment_PreconditionNotFulfilled::OAuthServerRouteEndpointAccessibleController_SyncError::OAuthServerServiceEndpointAccessibleController_SyncError::OAuthServerServiceEndpointsEndpointAccessibleController_SyncError::WellKnownReadyController_SyncError
    status: "True"
    type: Degraded
  - lastTransitionTime: "2023-03-08T12:17:48Z"
    message: 'AuthenticatorCertKeyProgressing: All is well'
    reason: AsExpected
    status: "False"
    type: Progressing
  - lastTransitionTime: "2023-03-08T12:08:35Z"
    message: |-
      OAuthServerServiceEndpointAccessibleControllerAvailable: Get "https://172.30.76.170:443/healthz": dial tcp 172.30.76.170:443: connect: connection refused
      OAuthServerServiceEndpointsEndpointAccessibleControllerAvailable: endpoints "oauth-openshift" not found
      WellKnownAvailable: The well-known endpoint is not yet available: failed to get oauth metadata from openshift-config-managed/oauth-openshift ConfigMap: configmap "oauth-openshift" not found (check authentication operator, it is supposed to create this)
    reason: OAuthServerDeployment_PreconditionNotFulfilled::OAuthServerServiceEndpointAccessibleController_EndpointUnavailable::OAuthServerServiceEndpointsEndpointAccessibleController_ResourceNotFound::WellKnown_NotReady
    status: "False"
    type: Available
  - lastTransitionTime: "2023-03-08T12:08:34Z"
    message: All is well
    reason: AsExpected
    status: "True"
    type: Upgradeable
  extension: null
  relatedObjects:
  - group: operator.openshift.io
    name: cluster
    resource: authentications
  - group: config.openshift.io
    name: cluster
    resource: authentications
  - group: config.openshift.io
    name: cluster
    resource: infrastructures
  - group: config.openshift.io
    name: cluster
    resource: oauths
  - group: route.openshift.io
    name: oauth-openshift
    namespace: openshift-authentication
    resource: routes
  - group: ""
    name: oauth-openshift
    namespace: openshift-authentication
    resource: services
  - group: ""
    name: openshift-config
    resource: namespaces
  - group: ""
    name: openshift-config-managed
    resource: namespaces
  - group: ""
    name: openshift-authentication
    resource: namespaces
  - group: ""
    name: openshift-authentication-operator
    resource: namespaces
  - group: ""
    name: openshift-ingress
    resource: namespaces
  - group: ""
    name: openshift-oauth-apiserver
    resource: namespaces
  versions:
  - name: operator
    version: 4.13.0-ec.4
  - name: oauth-apiserver
    version: 4.13.0-ec.4
